/** Declaration file generated by dts-gen */

export class ConstraintBuilder {
    constructor(e: any, n: any);

    addConstraint(t: any, e: any): any;

    addValueConstraint(t: any, e: any): any;

    build(t: any, e: any): any;

    callConstraintFn(t: any, e: any, n: any, r: any): any;

    isMultiArgsCall(t: any): any;

    isNoValueConstraint(t: any): any;

    multiValueConstraint(t: any, e: any): any;

    nonPresentConstraintValue(t: any, e: any): any;

    onConstraintAdded(t: any): any;

    presentConstraintValue(t: any, e: any): any;

    valErrMessage(t: any): any;

}

export class ErrorMessageHandler {
    constructor(e: any, n: any);

    errMessageFor(t: any): any;

    valErrMessage(t: any): any;

}

export class PropertyValueResolver {
    constructor(e: any, n: any);

    createMultiTypeResolver(): any;

    createSingleTypeResolver(): any;

    defaultType(): void;

    initResolvers(): void;

    resolve(): any;

    toDefaultEntry(): any;

    toMultiType(): any;

    toSingleType(): any;

}

export class YupBuilder {
    constructor(e: any, n: any);

    additionalPropsToShape(t: any, e: any): any;

    createYupSchemaEntry(t: any): any;

    getAdditionalProperties(t: any): any;

    getName(t: any): any;

    getProps(t: any): any;

    getRequired(t: any): any;

    getType(t: any): any;

    init(t: any, e: any): any;

    isRequired(t: any): any;

    normalizeRequired(): any;

    objPropsToShape(t: any): any;

    propToYupSchemaEntry(t: any): any;

    propsToShape(t: any): any;

    setLocale(): void;

}

export class YupSchemaEntry {
    constructor(e: any);

    createPropertyValueHandler(t: any, e: any): any;

    error(t: any, e: any): void;

    isValidSchema(): any;

    setPropertyHandler(): void;

    setTypeHandlers(): void;

    toEntry(): any;

}

export function YupSchemaEntryError(...args: any[]): any;

export function buildYup(t: any, e: any): any;

export function createPropertyValueResolver(t: any, e: any, n: any): any;

export function createYupSchemaEntry(t: any): any;

export function extendYupApi(e: any): any;

export namespace YupSchemaEntryError {
    const stackTraceLimit: number;

    function captureStackTrace(p0: any, p1: any): any;

}

export namespace types {
    class Base {
        constructor(e: any);

        createSchemaParserBuilder(t: any, e: any): any;

    }

    class YupArray {
        constructor(e: any);

        $additionalItems(): any;

        $contains(): any;

        $items(): any;

        $uniqueItems(): any;

        compact(): any;

        convert(): any;

        ensureItems(): any;

        handleInvalidSize(t: any, e: any): any;

        isValidSize(t: any): any;

        itemsOf(): any;

        maxItems(): any;

        minItems(): any;

        static create(t: any): any;

    }

    class YupBoolean {
        constructor(e: any);

        static create(t: any): any;

    }

    class YupDate {
        constructor(e: any);

        convert(): any;

        handleInvalidDate(t: any, e: any): any;

        isValidDate(t: any): any;

        isValidDateType(t: any): any;

        maxDate(): any;

        minDate(): any;

        toDate(t: any): any;

        transformToDate(t: any): any;

        static create(t: any): any;

    }

    class YupMixed {
        constructor(e: any);

        addConstraint(t: any, e: any): any;

        addMappedConstraint(t: any): void;

        addMappedConstraints(): any;

        addValueConstraint(t: any, e: any): any;

        apply(t: any, ...args: any[]): any;

        builtInConvertFnFor(t: any): any;

        configureTypeConfig(): void;

        convert(): any;

        convertEnabled(): void;

        convertFnFor(t: any): any;

        createConstraintBuilder(t: any, e: any): any;

        createErrorMessageHandler(t: any, e: any): any;

        createSchemaEntry(): any;

        createWhenConditionFor(t: any): any;

        customConvertFnFor(t: any): any;

        deNormalize(): void;

        disabledMode(t: any): any;

        enabledMode(t: any): any;

        errMessage(t: any): any;

        error(t: any, e: any): void;

        errorMsg(t: any): void;

        getBase(): any;

        getConstraints(): any;

        getValidator(): any;

        init(t: any): void;

        initHelpers(): void;

        isRequired(t: any): any;

        isType(): any;

        label(): any;

        message(): any;

        normalize(): void;

        notOneOf(): any;

        nullable(): any;

        oneOf(): any;

        preProcessedConstraintValue(t: any): any;

        rebind(...args: any[]): void;

        throwError(t: any): void;

        toValidJSONSchema(): void;

        valErrMessage(t: any): any;

        validateOnCreate(t: any, e: any, n: any): void;

        when(): any;

    }

    class YupNumber {
        constructor(e: any);

        convert(): any;

        integer(): any;

        negative(): any;

        normalize(): void;

        normalizeNumType(t: any): any;

        posNeg(): void;

        positive(): any;

        range(): void;

        round(): any;

        truncate(): any;

        static create(t: any): any;

        static schemaEntryFor(t: any): any;

    }

    class YupObject {
        constructor(e: any);

        camelCase(): any;

        constantCase(): any;

        convert(): any;

        noUnknown(): any;

        static create(t: any): any;

    }

    class YupString {
        constructor(e: any);

        constraintNameFor(...args: any[]): any;

        convert(): any;

        email(): any;

        genericFormat(): void;

        lowercase(): any;

        maxLength(): any;

        minLength(): any;

        normalize(): void;

        pattern(): any;

        trim(): any;

        uppercase(): any;

        url(): any;

        static create(t: any): any;

    }

    const errValKeys: string[];

    function ConvertYupSchemaError(...args: any[]): any;

    function toYupArray(t: any, e: any): any;

    function toYupBoolean(t: any, e: any): any;

    function toYupDate(t: any, e: any): any;

    function toYupNumber(t: any, e: any): any;

    function toYupNumberSchemaEntry(t: any, e: any): any;

    function toYupObject(t: any, e: any): any;

    function toYupString(t: any, e: any): any;

    namespace ConvertYupSchemaError {
        const stackTraceLimit: number;

        function captureStackTrace(p0: any, p1: any): any;

    }

    namespace defaults {
        function errMessages(t: any): any;

    }

}

